# Billing foundation (PLAN 9.2), applied in the management (payer) account: a CUR 2.0 data export, Cost Anomaly
# Detection per OU, and cost allocation tags for the CostCenter showback. Per-account budgets are governance/budgets.

data "aws_caller_identity" "current" {}
data "aws_partition" "current" {}
data "aws_region" "current" {}

locals {
  account_id  = data.aws_caller_identity.current.account_id
  partition   = data.aws_partition.current.partition
  bucket_name = "${var.name}-cur-${local.account_id}-${data.aws_region.current.region}"
  s3_prefix   = "cur2"
}

# ------------------------------------------------------------------------------
# Bucket for the export
# ------------------------------------------------------------------------------
resource "aws_s3_bucket" "cur" {
  #checkov:skip=CKV_AWS_18: "Access logging needs the log-archive bucket (PLAN 4.1); CloudTrail data events cover it and the bucket only receives AWS billing writes"
  #checkov:skip=CKV_AWS_144: "Billing exports can be regenerated by AWS for the past months; cross-region replication would double the storage for no recovery gain"
  #checkov:skip=CKV_AWS_145: "SSE-S3: the billing service writes with its own principal and a customer-managed key would need a key policy for it; the data is aggregate cost, classified internal"
  #checkov:skip=CKV2_AWS_62: "No consumers need event notifications"
  bucket = local.bucket_name
  tags   = merge({ Service = "governance-billing" }, var.tags)
}

resource "aws_s3_bucket_public_access_block" "cur" {
  bucket = aws_s3_bucket.cur.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "cur" {
  bucket = aws_s3_bucket.cur.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "cur" {
  bucket = aws_s3_bucket.cur.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "cur" {
  bucket = aws_s3_bucket.cur.id

  rule {
    id     = "expire-old-exports"
    status = "Enabled"

    filter {}

    expiration {
      days = var.export_retention_days
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  depends_on = [aws_s3_bucket_versioning.cur]
}

# Only the two billing services, writing on behalf of THIS account's exports, may put objects. TLS only.
data "aws_iam_policy_document" "cur" {
  statement {
    sid       = "AllowBillingServicesToWrite"
    effect    = "Allow"
    actions   = ["s3:PutObject", "s3:GetBucketPolicy"]
    resources = [aws_s3_bucket.cur.arn, "${aws_s3_bucket.cur.arn}/*"]

    principals {
      type        = "Service"
      identifiers = ["billingreports.amazonaws.com", "bcm-data-exports.amazonaws.com"]
    }

    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"
      values   = [local.account_id]
    }

    condition {
      test     = "StringLike"
      variable = "aws:SourceArn"
      values = [
        "arn:${local.partition}:cur:us-east-1:${local.account_id}:definition/*",
        "arn:${local.partition}:bcm-data-exports:us-east-1:${local.account_id}:export/*",
      ]
    }
  }

  statement {
    sid       = "DenyInsecureTransport"
    effect    = "Deny"
    actions   = ["s3:*"]
    resources = [aws_s3_bucket.cur.arn, "${aws_s3_bucket.cur.arn}/*"]

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

resource "aws_s3_bucket_policy" "cur" {
  bucket = aws_s3_bucket.cur.id
  policy = data.aws_iam_policy_document.cur.json

  depends_on = [aws_s3_bucket_public_access_block.cur]
}

# ------------------------------------------------------------------------------
# CUR 2.0 (Data Exports): daily, Parquet, with resource IDs, ready for Athena.
# ------------------------------------------------------------------------------
resource "aws_bcmdataexports_export" "cur" {
  provider = aws.us_east_1

  export {
    name = "${var.name}-cur2"

    data_query {
      query_statement = "SELECT * FROM COST_AND_USAGE_REPORT"
      table_configurations = {
        COST_AND_USAGE_REPORT = {
          TIME_GRANULARITY                      = "DAILY"
          INCLUDE_RESOURCES                     = "TRUE"
          INCLUDE_MANUAL_DISCOUNT_COMPATIBILITY = "FALSE"
          INCLUDE_SPLIT_COST_ALLOCATION_DATA    = "FALSE"
        }
      }
    }

    destination_configurations {
      s3_destination {
        s3_bucket = aws_s3_bucket.cur.id
        s3_prefix = local.s3_prefix
        s3_region = data.aws_region.current.region

        s3_output_configurations {
          compression = "PARQUET"
          format      = "PARQUET"
          output_type = "CUSTOM"
          overwrite   = "OVERWRITE_REPORT"
        }
      }
    }

    refresh_cadence {
      frequency = "SYNCHRONOUS"
    }
  }

  depends_on = [aws_s3_bucket_policy.cur]
}

# ------------------------------------------------------------------------------
# Cost Anomaly Detection: one monitor for the whole organization by service, and one per OU by linked account.
# ------------------------------------------------------------------------------
resource "aws_ce_anomaly_monitor" "services" {
  name              = "${var.name}-by-service"
  monitor_type      = "DIMENSIONAL"
  monitor_dimension = "SERVICE"
  tags              = var.tags
}

resource "aws_ce_anomaly_monitor" "ou" {
  for_each = { for ou, ids in var.anomaly_ou_accounts : ou => ids if length(ids) > 0 }

  name         = "${var.name}-ou-${lower(each.key)}"
  monitor_type = "CUSTOM"
  monitor_specification = jsonencode({
    Dimensions = {
      Key          = "LINKED_ACCOUNT"
      Values       = each.value
      MatchOptions = ["EQUALS"]
    }
  })
  tags = var.tags
}

resource "aws_ce_anomaly_subscription" "daily" {
  name             = "${var.name}-daily"
  frequency        = "DAILY"
  monitor_arn_list = concat([aws_ce_anomaly_monitor.services.arn], [for m in aws_ce_anomaly_monitor.ou : m.arn])

  dynamic "subscriber" {
    for_each = toset(var.anomaly_alert_emails)

    content {
      type    = "EMAIL"
      address = subscriber.value
    }
  }

  threshold_expression {
    dimension {
      key           = "ANOMALY_TOTAL_IMPACT_ABSOLUTE"
      match_options = ["GREATER_THAN_OR_EQUAL"]
      values        = [tostring(var.anomaly_threshold_usd)]
    }
  }

  tags = var.tags
}

# ------------------------------------------------------------------------------
# Cost allocation tags: what makes a CostCenter showback possible.
# ------------------------------------------------------------------------------
resource "aws_ce_cost_allocation_tag" "this" {
  for_each = toset(var.cost_allocation_tags)

  tag_key = each.value
  status  = "Active"
}
